### ISSUE TITLE
Size ?

### ISSUE THREAD

**Issue by herocoder14** [shriekdj/ubuntu-on-termux#2]
What can be the estimated size of software ?
And what does it look like ?
Can I get a screenshot?

**Comment by shriekdj** [comment]
@herocoder14 , are you still waiting for reply. if yes i can send a screenshot and size details?

**Comment by shriekdj** [comment]
@herocoder14 , I just ignored this repository as there was nothing to update.

**Comment by herocoder14** [comment]
Good to see you are still active 👍.
So can you upload a screenshot on readme file/landing page.
Also add a selection of Minimal and Advanced install in which basic packages like python3 are downloaded.
And, I am closing this issue now...

**Comment by shriekdj** [comment]
@herocoder14 , I reinstalled the latest version which took 374 MB Storage for Termux for Me Given below is screenshot of Storage and the installation process also updated in direct installation section with verticle panorama image of installation process.

**Comment by shriekdj** [comment]
![Screenshot_20240605-193259](https://github.com/shriekdj/ubuntu-on-termux/assets/35664193/a4529a3d-b331-437a-b801-9569c04a2d44)

**Comment by shriekdj** [comment]
I used my friend's device. it's model was moto g52 if you need that detail.
